language: generic
sudo: required
services:
    - docker
# Things to do before running the tests
before_install:
    - docker build -t olaishola05/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true olaishola05/docker-react npm run test